# Generated by Django 3.2.4 on 2024-06-07 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_prof_photo'),
        ('post', '0002_alter_post_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_by',
            field=models.ForeignKey(default='8bbf7f2ece5745a1b54aa5879fe50359', on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_by',
            field=models.ForeignKey(default='8bbf7f2ece5745a1b54aa5879fe50359', on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
            preserve_default=False,
        ),
    ]
