# Generated by Django 3.2.4 on 2024-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prof_photo',
            field=models.ImageField(blank=True, default='default-photo.jpg', null=True, upload_to='profiles'),
        ),
    ]
